# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bueddl/Desktop/NixCompress

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bueddl/Desktop/NixCompress

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bueddl/Desktop/NixCompress/CMakeFiles /home/bueddl/Desktop/NixCompress/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bueddl/Desktop/NixCompress/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nc

# Build rule for target.
nc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nc
.PHONY : nc

# fast build rule for target.
nc/fast:
	$(MAKE) -f CMakeFiles/nc.dir/build.make CMakeFiles/nc.dir/build
.PHONY : nc/fast

source/archive.o: source/archive.c.o
.PHONY : source/archive.o

# target to build an object file
source/archive.c.o:
	$(MAKE) -f CMakeFiles/nc.dir/build.make CMakeFiles/nc.dir/source/archive.c.o
.PHONY : source/archive.c.o

source/archive.i: source/archive.c.i
.PHONY : source/archive.i

# target to preprocess a source file
source/archive.c.i:
	$(MAKE) -f CMakeFiles/nc.dir/build.make CMakeFiles/nc.dir/source/archive.c.i
.PHONY : source/archive.c.i

source/archive.s: source/archive.c.s
.PHONY : source/archive.s

# target to generate assembly for a file
source/archive.c.s:
	$(MAKE) -f CMakeFiles/nc.dir/build.make CMakeFiles/nc.dir/source/archive.c.s
.PHONY : source/archive.c.s

source/args.o: source/args.c.o
.PHONY : source/args.o

# target to build an object file
source/args.c.o:
	$(MAKE) -f CMakeFiles/nc.dir/build.make CMakeFiles/nc.dir/source/args.c.o
.PHONY : source/args.c.o

source/args.i: source/args.c.i
.PHONY : source/args.i

# target to preprocess a source file
source/args.c.i:
	$(MAKE) -f CMakeFiles/nc.dir/build.make CMakeFiles/nc.dir/source/args.c.i
.PHONY : source/args.c.i

source/args.s: source/args.c.s
.PHONY : source/args.s

# target to generate assembly for a file
source/args.c.s:
	$(MAKE) -f CMakeFiles/nc.dir/build.make CMakeFiles/nc.dir/source/args.c.s
.PHONY : source/args.c.s

source/bin-tree.o: source/bin-tree.c.o
.PHONY : source/bin-tree.o

# target to build an object file
source/bin-tree.c.o:
	$(MAKE) -f CMakeFiles/nc.dir/build.make CMakeFiles/nc.dir/source/bin-tree.c.o
.PHONY : source/bin-tree.c.o

source/bin-tree.i: source/bin-tree.c.i
.PHONY : source/bin-tree.i

# target to preprocess a source file
source/bin-tree.c.i:
	$(MAKE) -f CMakeFiles/nc.dir/build.make CMakeFiles/nc.dir/source/bin-tree.c.i
.PHONY : source/bin-tree.c.i

source/bin-tree.s: source/bin-tree.c.s
.PHONY : source/bin-tree.s

# target to generate assembly for a file
source/bin-tree.c.s:
	$(MAKE) -f CMakeFiles/nc.dir/build.make CMakeFiles/nc.dir/source/bin-tree.c.s
.PHONY : source/bin-tree.c.s

source/huffman.o: source/huffman.c.o
.PHONY : source/huffman.o

# target to build an object file
source/huffman.c.o:
	$(MAKE) -f CMakeFiles/nc.dir/build.make CMakeFiles/nc.dir/source/huffman.c.o
.PHONY : source/huffman.c.o

source/huffman.i: source/huffman.c.i
.PHONY : source/huffman.i

# target to preprocess a source file
source/huffman.c.i:
	$(MAKE) -f CMakeFiles/nc.dir/build.make CMakeFiles/nc.dir/source/huffman.c.i
.PHONY : source/huffman.c.i

source/huffman.s: source/huffman.c.s
.PHONY : source/huffman.s

# target to generate assembly for a file
source/huffman.c.s:
	$(MAKE) -f CMakeFiles/nc.dir/build.make CMakeFiles/nc.dir/source/huffman.c.s
.PHONY : source/huffman.c.s

source/linux/simple_draw.o: source/linux/simple_draw.c.o
.PHONY : source/linux/simple_draw.o

# target to build an object file
source/linux/simple_draw.c.o:
	$(MAKE) -f CMakeFiles/nc.dir/build.make CMakeFiles/nc.dir/source/linux/simple_draw.c.o
.PHONY : source/linux/simple_draw.c.o

source/linux/simple_draw.i: source/linux/simple_draw.c.i
.PHONY : source/linux/simple_draw.i

# target to preprocess a source file
source/linux/simple_draw.c.i:
	$(MAKE) -f CMakeFiles/nc.dir/build.make CMakeFiles/nc.dir/source/linux/simple_draw.c.i
.PHONY : source/linux/simple_draw.c.i

source/linux/simple_draw.s: source/linux/simple_draw.c.s
.PHONY : source/linux/simple_draw.s

# target to generate assembly for a file
source/linux/simple_draw.c.s:
	$(MAKE) -f CMakeFiles/nc.dir/build.make CMakeFiles/nc.dir/source/linux/simple_draw.c.s
.PHONY : source/linux/simple_draw.c.s

source/list.o: source/list.c.o
.PHONY : source/list.o

# target to build an object file
source/list.c.o:
	$(MAKE) -f CMakeFiles/nc.dir/build.make CMakeFiles/nc.dir/source/list.c.o
.PHONY : source/list.c.o

source/list.i: source/list.c.i
.PHONY : source/list.i

# target to preprocess a source file
source/list.c.i:
	$(MAKE) -f CMakeFiles/nc.dir/build.make CMakeFiles/nc.dir/source/list.c.i
.PHONY : source/list.c.i

source/list.s: source/list.c.s
.PHONY : source/list.s

# target to generate assembly for a file
source/list.c.s:
	$(MAKE) -f CMakeFiles/nc.dir/build.make CMakeFiles/nc.dir/source/list.c.s
.PHONY : source/list.c.s

source/main.o: source/main.c.o
.PHONY : source/main.o

# target to build an object file
source/main.c.o:
	$(MAKE) -f CMakeFiles/nc.dir/build.make CMakeFiles/nc.dir/source/main.c.o
.PHONY : source/main.c.o

source/main.i: source/main.c.i
.PHONY : source/main.i

# target to preprocess a source file
source/main.c.i:
	$(MAKE) -f CMakeFiles/nc.dir/build.make CMakeFiles/nc.dir/source/main.c.i
.PHONY : source/main.c.i

source/main.s: source/main.c.s
.PHONY : source/main.s

# target to generate assembly for a file
source/main.c.s:
	$(MAKE) -f CMakeFiles/nc.dir/build.make CMakeFiles/nc.dir/source/main.c.s
.PHONY : source/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... nc"
	@echo "... source/archive.o"
	@echo "... source/archive.i"
	@echo "... source/archive.s"
	@echo "... source/args.o"
	@echo "... source/args.i"
	@echo "... source/args.s"
	@echo "... source/bin-tree.o"
	@echo "... source/bin-tree.i"
	@echo "... source/bin-tree.s"
	@echo "... source/huffman.o"
	@echo "... source/huffman.i"
	@echo "... source/huffman.s"
	@echo "... source/linux/simple_draw.o"
	@echo "... source/linux/simple_draw.i"
	@echo "... source/linux/simple_draw.s"
	@echo "... source/list.o"
	@echo "... source/list.i"
	@echo "... source/list.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

